=== axelwass/oliveira/Conversations/xml/conv.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT conversacion (herencia?,PNJ,PJ)>
<!ELEMENT PJ (lineas?)>
<!ELEMENT PNJ (lineas?,muletillas?)>
<!ELEMENT lineas (temas,respuestas+)>
<!ELEMENT temas (tema)*>
<!ELEMENT tema (texto)>
<!ATTLIST tema idRef CDATA "">
<!ELEMENT respuestas (respuesta)+>
<!ATTLIST respuestas id CDATA "">
<!ELEMENT respuesta (condicion?,texto,accion?)>
<!ATTLIST respuesta idRef CDATA "">
<!ELEMENT condicion (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT accion (#PCDATA)>
<!ELEMENT herencia (#PCDATA)>
<!ELEMENT muletillas (muletilla)+>
<!ELEMENT muletilla (#PCDATA)>
<!ATTLIST muletilla tipo (enojo|broma|confundido) "enojo">

=== axelwass/oliveira/Conversations/xml/conv1.xml
<!DOCTYPE xml SYSTEM "conv.dtd">
<conversacion>
	<PNJ>
		<lineas>
			<temas>
				<tema idRef="saludo">
					<texto>hola</texto></tema>
				<tema idRef="saludo">
					<texto>buenas tardes</texto>
				</tema>
			</temas>
			<respuestas id="saludo">
				<respuesta idRef="saludo">
					<texto>hola</texto>
				</respuesta>
				<respuesta idRef="saludo">
					<texto>buenas tardes</texto>
				</respuesta>
			</respuestas>
		</lineas>
	</PNJ>
	<PJ>
		<lineas>
			<temas></temas>
			<respuestas id="saludo">
				<respuesta idRef="saludo">
					<texto>hola</texto>
				</respuesta>
				<respuesta idRef="saludo">
					<texto>buenas nochas</texto>
				</respuesta>
			</respuestas>
		</lineas>
	</PJ>
</conversacion>
